#!/usr/bin/env bash
# Isolation and cleanup helpers for real-Treehouse tests that create temporary
# Git repositories.
#
# A real-Treehouse fixture must call fm_treehouse_test_isolation_prepare before
# any Treehouse command can run for the temporary project.
# The helper binds a repository-local treehouse.toml and all pool state to the
# exact temporary root, disables the update cache, and records an immutable
# structural ownership marker.
#
# fm_treehouse_test_install_shim places a fixed test-owned wrapper first on PATH
# so Treehouse commands launched inside a runtime pane also disable update-cache
# writes while the repository-local config keeps pool state isolated.
#
# fm_treehouse_test_pool_cleanup uses only Treehouse's supported return and
# exact-pool destroy lifecycle after revalidating the same isolation binding.
# fm_treehouse_test_root_cleanup removes the temporary root only after every
# managed pool is empty, so success, failure, interruption, and repeated cleanup
# converge without deleting a Treehouse worktree directly.

fm_treehouse_test_realpath_dir() { # <existing-directory>
  (cd "$1" 2>/dev/null && pwd -P)
}

fm_treehouse_test_path_is_within() { # <child> <parent>
  case "$1" in
    "$2"/*) return 0 ;;
    *) return 1 ;;
  esac
}

fm_treehouse_test_ambient_root() {
  local home_abs
  [ -n "${HOME:-}" ] && [ -d "$HOME" ] || return 1
  home_abs=$(fm_treehouse_test_realpath_dir "$HOME") || return 1
  printf '%s/.treehouse\n' "$home_abs"
}

fm_treehouse_test_validate_root_project() { # <test-temp-root> <temporary-project>
  local test_root=${1:-} project=${2:-} root_abs project_abs ambient
  [ -n "$test_root" ] && [ -n "$project" ] || {
    echo "treehouse test isolation: exact test root and project are required" >&2
    return 1
  }
  [ -d "$test_root" ] && [ -d "$project/.git" ] || {
    echo "treehouse test isolation: test root and Git project must already exist" >&2
    return 1
  }
  root_abs=$(fm_treehouse_test_realpath_dir "$test_root") || return 1
  project_abs=$(fm_treehouse_test_realpath_dir "$project") || return 1
  [ "$root_abs" != / ] || {
    echo "treehouse test isolation: refusing filesystem root" >&2
    return 1
  }
  fm_treehouse_test_path_is_within "$project_abs" "$root_abs" || {
    echo "treehouse test isolation: refusing project outside the exact test root: $project_abs" >&2
    return 1
  }
  ambient=$(fm_treehouse_test_ambient_root || true)
  if [ -n "$ambient" ]; then
    case "$root_abs" in
      "$ambient"|"$ambient"/*)
        echo "treehouse test isolation: refusing a test root in the ambient Treehouse home: $root_abs" >&2
        return 1
        ;;
    esac
  fi
  case "$root_abs$project_abs" in
    *$'\n'*|*$'\r'*|*\"*|*\\*)
      echo "treehouse test isolation: path cannot be encoded safely in generated Treehouse config" >&2
      return 1
      ;;
  esac
  printf '%s\n%s\n' "$root_abs" "$project_abs"
}

fm_treehouse_test_isolation_prepare() { # <test-temp-root> <temporary-project>
  local test_root=${1:-} project=${2:-} paths root_abs project_abs state_root
  local marker config expected_marker expected_config marker_tmp config_tmp
  paths=$(fm_treehouse_test_validate_root_project "$test_root" "$project") || return 1
  root_abs=${paths%%$'\n'*}
  project_abs=${paths#*$'\n'}
  state_root="$root_abs/treehouse-state"
  marker="$root_abs/.fm-treehouse-test-isolation"
  config="$project_abs/treehouse.toml"
  expected_marker=$(printf 'version=1\nroot=%s\nstate_root=%s' "$root_abs" "$state_root")
  expected_config=$(printf '# Generated by tests/treehouse-test-safety.sh.\nmax_trees = 16\nroot = "%s"' "$state_root")

  if [ -e "$marker" ] && [ "$(cat "$marker" 2>/dev/null)" != "$expected_marker" ]; then
    echo "treehouse test isolation: refusing malformed or foreign ownership marker" >&2
    return 1
  fi
  if [ -e "$config" ] && [ "$(cat "$config" 2>/dev/null)" != "$expected_config" ]; then
    echo "treehouse test isolation: refusing existing project Treehouse config" >&2
    return 1
  fi

  mkdir -p "$state_root"
  [ "$(fm_treehouse_test_realpath_dir "$state_root")" = "$state_root" ] || {
    echo "treehouse test isolation: state root did not resolve exactly below the test root" >&2
    return 1
  }
  fm_treehouse_test_path_is_within "$state_root" "$root_abs" || return 1

  umask 077
  marker_tmp="$root_abs/.fm-treehouse-test-isolation.tmp.$$"
  config_tmp="$project_abs/.treehouse.toml.tmp.$$"
  printf '%s\n' "$expected_marker" > "$marker_tmp"
  printf '%s\n' "$expected_config" > "$config_tmp"
  mv "$marker_tmp" "$marker"
  mv "$config_tmp" "$config"
  export TREEHOUSE_NO_UPDATE_CHECK=1
  fm_treehouse_test_isolation_assert "$root_abs" "$project_abs"
}

fm_treehouse_test_isolation_assert() { # <test-temp-root> <temporary-project>
  local test_root=${1:-} project=${2:-} paths root_abs project_abs state_root
  local marker config expected_marker expected_config ambient
  paths=$(fm_treehouse_test_validate_root_project "$test_root" "$project") || return 1
  root_abs=${paths%%$'\n'*}
  project_abs=${paths#*$'\n'}
  state_root="$root_abs/treehouse-state"
  marker="$root_abs/.fm-treehouse-test-isolation"
  config="$project_abs/treehouse.toml"
  expected_marker=$(printf 'version=1\nroot=%s\nstate_root=%s' "$root_abs" "$state_root")
  expected_config=$(printf '# Generated by tests/treehouse-test-safety.sh.\nmax_trees = 16\nroot = "%s"' "$state_root")

  [ -d "$state_root" ] && [ "$(fm_treehouse_test_realpath_dir "$state_root")" = "$state_root" ] || {
    echo "treehouse test isolation: missing or redirected state root" >&2
    return 1
  }
  [ -f "$marker" ] && [ "$(cat "$marker" 2>/dev/null)" = "$expected_marker" ] || {
    echo "treehouse test isolation: ownership marker does not match the exact root" >&2
    return 1
  }
  [ -f "$config" ] && [ "$(cat "$config" 2>/dev/null)" = "$expected_config" ] || {
    echo "treehouse test isolation: repository config does not bind the exact state root" >&2
    return 1
  }
  ambient=$(fm_treehouse_test_ambient_root || true)
  if [ -n "$ambient" ]; then
    case "$state_root/.treehouse" in
      "$ambient"|"$ambient"/*)
        echo "treehouse test isolation: effective pool root overlaps the ambient Treehouse home" >&2
        return 1
        ;;
    esac
  fi
  export TREEHOUSE_NO_UPDATE_CHECK=1
}

fm_treehouse_test_install_shim() { # <test-temp-root> <temporary-project> <real-treehouse>
  local test_root=$1 project=$2 real_treehouse=$3 root_abs shim_dir
  fm_treehouse_test_isolation_assert "$test_root" "$project" || return 1
  [ -x "$real_treehouse" ] || {
    echo "treehouse test isolation: real Treehouse executable is required" >&2
    return 1
  }
  root_abs=$(fm_treehouse_test_realpath_dir "$test_root") || return 1
  shim_dir="$root_abs/treehouse-bin"
  mkdir -p "$shim_dir"
  cat > "$shim_dir/treehouse" <<'SH'
#!/usr/bin/env bash
set -u
: "${FM_TREEHOUSE_TEST_REAL_TREEHOUSE:?missing isolated real Treehouse path}"
exec env TREEHOUSE_NO_UPDATE_CHECK=1 "$FM_TREEHOUSE_TEST_REAL_TREEHOUSE" "$@"
SH
  chmod 0755 "$shim_dir/treehouse"
  FM_TREEHOUSE_TEST_REAL_TREEHOUSE=$real_treehouse
  export FM_TREEHOUSE_TEST_REAL_TREEHOUSE
  PATH="$shim_dir:$PATH"
  export PATH
}

fm_treehouse_test_common_dir() { # <worktree>
  local worktree=$1 common
  common=$(git -C "$worktree" rev-parse --git-common-dir 2>/dev/null) || return 1
  case "$common" in
    /*) fm_treehouse_test_realpath_dir "$common" ;;
    *) fm_treehouse_test_realpath_dir "$worktree/$common" ;;
  esac
}

fm_treehouse_test_pool_cleanup() { # <test-temp-root> <temporary-project>
  local test_root=${1:-} project=${2:-} root_abs project_abs project_git state_root
  local status wt common pool='' candidate slot state_status process_count after

  [ -n "$test_root" ] && [ -n "$project" ] || return 0
  [ -e "$test_root" ] || return 0
  fm_treehouse_test_isolation_assert "$test_root" "$project" || return 1
  command -v treehouse >/dev/null 2>&1 || {
    echo "treehouse test cleanup: treehouse is required" >&2
    return 1
  }
  command -v jq >/dev/null 2>&1 || {
    echo "treehouse test cleanup: jq is required" >&2
    return 1
  }

  root_abs=$(fm_treehouse_test_realpath_dir "$test_root") || return 1
  project_abs=$(fm_treehouse_test_realpath_dir "$project") || return 1
  state_root="$root_abs/treehouse-state"
  project_git=$(fm_treehouse_test_realpath_dir "$project_abs/.git") || return 1

  status=$(cd "$project_abs" && treehouse status --json) || {
    echo "treehouse test cleanup: could not inspect the exact temporary project" >&2
    return 1
  }
  printf '%s' "$status" | jq -e 'type == "array"' >/dev/null 2>&1 || {
    echo "treehouse test cleanup: unexpected Treehouse status response" >&2
    return 1
  }
  [ "$(printf '%s' "$status" | jq 'length')" -gt 0 ] || return 0

  while IFS=$'\t' read -r wt state_status process_count; do
    [ -n "$wt" ] && [ -d "$wt" ] || {
      echo "treehouse test cleanup: status named a missing worktree" >&2
      return 1
    }
    case "$wt" in
      /*) ;;
      *)
        echo "treehouse test cleanup: status named a non-absolute worktree" >&2
        return 1
        ;;
    esac
    [ "$state_status" != leased ] || {
      echo "treehouse test cleanup: refusing leased worktree $wt" >&2
      return 1
    }
    [ "$process_count" -eq 0 ] || {
      echo "treehouse test cleanup: refusing worktree with running processes $wt" >&2
      return 1
    }
    common=$(fm_treehouse_test_common_dir "$wt") || {
      echo "treehouse test cleanup: could not resolve Git ownership for $wt" >&2
      return 1
    }
    [ "$common" = "$project_git" ] || {
      echo "treehouse test cleanup: refusing worktree not owned by $project_abs: $wt" >&2
      return 1
    }
    candidate=$(dirname "$(dirname "$wt")")
    fm_treehouse_test_path_is_within "$candidate" "$state_root/.treehouse" || {
      echo "treehouse test cleanup: refusing pool outside the bound state root: $candidate" >&2
      return 1
    }
    [ -f "$candidate/treehouse-state.json" ] || {
      echo "treehouse test cleanup: refusing path without exact pool state: $candidate" >&2
      return 1
    }
    slot=$(basename "$(dirname "$wt")")
    case "$slot" in
      ''|*[!0-9]*)
        echo "treehouse test cleanup: refusing unexpected pool slot for $wt" >&2
        return 1
        ;;
    esac
    if [ -n "$pool" ] && [ "$candidate" != "$pool" ]; then
      echo "treehouse test cleanup: refusing multiple pools for one temporary project" >&2
      return 1
    fi
    pool=$candidate
  done < <(printf '%s' "$status" | jq -r '.[] | [.path, .status, ((.processes // []) | length)] | @tsv')

  [ -n "$pool" ] || {
    echo "treehouse test cleanup: could not resolve the owned pool" >&2
    return 1
  }

  while IFS= read -r wt; do
    [ -n "$wt" ] || continue
    (cd "$project_abs" && treehouse return --force "$wt") >/dev/null || {
      echo "treehouse test cleanup: could not return owned worktree $wt" >&2
      return 1
    }
  done < <(printf '%s' "$status" | jq -r '.[].path')

  after=$(cd "$project_abs" && treehouse status --json) || return 1
  while IFS=$'\t' read -r wt state_status process_count; do
    [ -n "$wt" ] || continue
    [ "$state_status" != leased ] && [ "$process_count" -eq 0 ] || {
      echo "treehouse test cleanup: owned worktree did not become idle after return: $wt" >&2
      return 1
    }
    common=$(fm_treehouse_test_common_dir "$wt") || return 1
    [ "$common" = "$project_git" ] || {
      echo "treehouse test cleanup: ownership changed before pool destroy: $wt" >&2
      return 1
    }
    candidate=$(dirname "$(dirname "$wt")")
    [ "$candidate" = "$pool" ] || {
      echo "treehouse test cleanup: pool identity changed before destroy" >&2
      return 1
    }
  done < <(printf '%s' "$after" | jq -r '.[] | [.path, .status, ((.processes // []) | length)] | @tsv')

  treehouse destroy "$pool" --all --yes >/dev/null || {
    echo "treehouse test cleanup: exact owned pool destroy failed: $pool" >&2
    return 1
  }
  after=$(cd "$project_abs" && treehouse status --json) || return 1
  printf '%s' "$after" | jq -e 'type == "array" and length == 0' >/dev/null 2>&1 || {
    echo "treehouse test cleanup: owned pool still contains worktrees after destroy: $pool" >&2
    return 1
  }
}

fm_treehouse_test_root_cleanup() { # <test-temp-root>
  local test_root=${1:-} root_abs state_root marker state_file expected_marker
  [ -n "$test_root" ] && [ -e "$test_root" ] || return 0
  [ -d "$test_root" ] || {
    echo "treehouse test cleanup: exact test root is not a directory" >&2
    return 1
  }
  root_abs=$(fm_treehouse_test_realpath_dir "$test_root") || return 1
  [ "$root_abs" != / ] || return 1
  state_root="$root_abs/treehouse-state"
  marker="$root_abs/.fm-treehouse-test-isolation"

  if [ -e "$marker" ]; then
    expected_marker=$(printf 'version=1\nroot=%s\nstate_root=%s' "$root_abs" "$state_root")
    if [ "$(cat "$marker" 2>/dev/null)" != "$expected_marker" ]; then
      echo "treehouse test cleanup: refusing root with a foreign isolation marker" >&2
      return 1
    fi
  fi

  if [ -d "$state_root/.treehouse" ]; then
    command -v jq >/dev/null 2>&1 || return 1
    while IFS= read -r state_file; do
      [ -n "$state_file" ] || continue
      jq -e '(.worktrees == null) or (.worktrees | type == "array" and length == 0)' "$state_file" >/dev/null 2>&1 || {
        echo "treehouse test cleanup: refusing to remove root with managed worktrees: $state_file" >&2
        return 1
      }
    done < <(find "$state_root/.treehouse" -type f -name treehouse-state.json -print)
  elif find "$root_abs" -type f -name treehouse-state.json -print -quit | grep . >/dev/null 2>&1; then
    echo "treehouse test cleanup: refusing state outside the bound Treehouse root" >&2
    return 1
  fi

  rm -rf -- "$root_abs"
}
